### PR TITLE
Add storage of complex dict object in storage

### PR DESCRIPTION
**Pull request by jhprinz**

### CODE REVIEW

**Comment by jhprinz** [comment]
This adds the capability to store dictionaries that use storable objects as keys as is used in the MSTIS transition object.

**Comment by jhprinz** [comment]
It seems to work fine. Can you somehow get this into travis in another branch before really merging? The MSTIS notebook and nose tests passed on my machine.

**Comment by jhprinz** [comment]
I made the new dict store to only make to more special if the dict cannot be store in the usual way. That should keep it fast and small in most cases.

**Comment by dwhswenson** [comment]
Thanks; merging!

**Pull request merged**
